// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Api;

#nullable disable

namespace Sample.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sample.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Andriy@mail",
                            Name = "Andriy",
                            Phone = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Sam@mail",
                            Name = "Sam",
                            Phone = "456"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Sasha@mail",
                            Name = "Sasha",
                            Phone = "789"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Nick@mail",
                            Name = "Nick",
                            Phone = "791"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
